### PR TITLE
chore(FDS-457): [Monorepo] - update build dependencies

### PR DESCRIPTION
**Pull request by lordpixel**
# Update package dependencies

Dependencies are grouped into different categories depending on their use:

- Build, for packages that support package builds
- Style, for things that enforce coding style (lint, format, etc)
- Test, for testing purposes
- Other, dependencies that do not belong to any of the aforementioned categories

# Update log
| Package                                   | Group      | Before       | latest                                                                                        | After   | Comment                                                                                                                                                                  |
| ----------------------------------------- | ---------- | ------------ | --------------------------------------------------------------------------------------------- | ------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| babel/core                                | build      | 7.14.3       | [7.16.12](https://github.com/babel/babel/releases/tag/v7.16.12)                               | 7.16.12 |                                                                                                                                                                          |
| babel/parser                              | build      | 7.14.4       | [7.16.12](https://github.com/babel/babel/releases/tag/v7.16.12)                               | 7.16.12 |                                                                                                                                                                          |
| babel/plugin-proposal-class-properties    | build      | 7.13.0       | [7.16.7](https://github.com/babel/babel/releases/tag/v7.16.12)                                | 7.16.7  |                                                                                                                                                                          |
| babel/plugin-proposal-export-default-from | build      | 7.12.13      | [7.16.7](https://github.com/babel/babel/releases/tag/v7.16.12)                                | 7.16.7  |                                                                                                                                                                          |
| babel/plugin-proposal-optional-chaining   | build      | 7.14.2       | [7.16.7](https://github.com/babel/babel/releases/tag/v7.16.12)                                | 7.16.7  |                                                                                                                                                                          |
| babel/plugin-transform-modules-commonjs   | build      | 7.14.0       | [7.16.8](https://github.com/babel/babel/releases/tag/v7.16.12)                                | 7.16.8  |                                                                                                                                                                          |
| babel/plugin-transform-runtime            | build      | 7.14.3       | [7.16.10](https://github.com/babel/babel/releases/tag/v7.16.12)                               | 7.16.10 |                                                                                                                                                                          |
| babel/preset-env                          | build      | 7.14.4       | [7.16.11](https://github.com/babel/babel/releases/tag/v7.16.12)                               | 7.16.11 |                                                                                                                                                                          |
| babel/preset-react                        | build      | 7.13.13      | [7.16.7](https://github.com/babel/babel/releases/tag/v7.16.12)                                | 7.16.7  |                                                                                                                                                                          |
| bjeco/prettier-config                     | style      | 0.1.6        |                                                                                               |         |                                                                                                                                                                          |
| changesets/cli                            | style      | 2.17.0       | [2.20.0](https://github.com/changesets/changesets/releases/tag/%40changesets%2Fcli%402.20.0)  | 2.20.0  |                                                                                                                                                                          |
| espressive/eslint-config                  | style      | workspace:\* |                                                                                               |         |                                                                                                                                                                          |
| fluentui/react-northstar                  | build      | 0.60.1       |                                                                                               |         |                                                                                                                                                                          |
| rollup/plugin-babel                       | build      | 5.3.0        |                                                                                               |         |                                                                                                                                                                          |
| rollup/plugin-json                        | build      | 4.1.0        |                                                                                               |         |                                                                                                                                                                          |
| rollup/plugin-node-resolve                | build      | 11.2.1       | [13.1.3](https://github.com/rollup/plugins/tree/master/packages/node-resolve/#readme)         | 13.1.3  |                                                                                                                                                                          |
| testing-library/dom                       | test       | 7.31.2       | [8.11.3](https://github.com/testing-library/dom-testing-library/releases/tag/v8.11.3)         |         |                                                                                                                                                                          |
| testing-library/jest-dom                  | test       | 5.13.0       | [5.16.1](https://github.com/testing-library/jest-dom/releases/tag/v5.16.1)                    | 5.16.1  |                                                                                                                                                                          |
| testing-library/react                     | test       | 11.2.7       | [12.1.2](https://github.com/testing-library/react-testing-library/releases/tag/v12.1.2)       | 12.1.2  | [read more](https://github.com/testing-library/dom-testing-library/releases/tag/v8.0.0)                                                                                  |
| testing-library/user-event                | test       | 13.1.9       | [13.5.0](https://github.com/testing-library/user-event/releases/tag/v13.5.0)                  | 13.5.0  |                                                                                                                                                                          |
| types/react                               | typescript | 16.8.0       | [17.0.38]()                                                                                   |         |                                                                                                                                                                          |
| types/react-dom                           | typescript | 16.8.0       | [17.0.11]()                                                                                   |         |                                                                                                                                                                          |
| typescript-eslint/eslint-plugin           | typescript | 4.26.0       | [5.10.1](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.10.1)         | 5.10.1  |                                                                                                                                                                          |
| typescript-eslint/parser                  | typescript | 4.26.0       | [5.10.1]()                                                                                    |         |                                                                                                                                                                          |
| babel-eslint                              | style      | 10.1.0       |                                                                                               |         |                                                                                                                                                                          |
| babel-jest                                | test       | 26.6.3       | [27.4.7](https://github.com/facebook/jest/releases/tag/v27.4.7)                               | 27.4.7  | [BREAKING](https://github.com/facebook/jest/releases/tag/v27.0.0)                                                                                                        |
| commitizen                                | style      | 4.2.4        |                                                                                               |         |                                                                                                                                                                          |
| cz-conventional-changelog                 | style      | 3.3.0        |                                                                                               |         |                                                                                                                                                                          |
| danger                                    | style      | 10.8.0       |                                                                                               |         |                                                                                                                                                                          |
| dotenv                                    | other      | 8.2.0        | [14.3.2]()                                                                                    |         |                                                                                                                                                                          |
| eslint                                    | style      | 7.32.0       |                                                                                               |         |                                                                                                                                                                          |
| eslint-plugin-deprecate                   | style      | 0.7.0        |                                                                                               |         |                                                                                                                                                                          |
| eslint-plugin-eslint-comments             | style      | 3.2.0        |                                                                                               |         |                                                                                                                                                                          |
| eslint-plugin-flowtype                    | style      | 6.1.0        |                                                                                               |         |                                                                                                                                                                          |
| eslint-plugin-import                      | style      | 2.24.2       | [2.25.4](https://github.com/import-js/eslint-plugin-import/releases/tag/v2.25.4)              | 2.25.4  |                                                                                                                                                                          |
| eslint-plugin-jest                        | style      | 24.4.2       | [26.0.0](https://github.com/jest-community/eslint-plugin-jest/releases/tag/v26.0.0)           |         | This version drops support for @typescript-eslint/eslint-plugin@4, we need to upgrade both [read more](https://github.com/jest-community/eslint-plugin-jest/issues/1035) |
| eslint-plugin-json-format                 | style      | 2.0.1        |                                                                                               |         |                                                                                                                                                                          |
| eslint-plugin-jsx-a11y                    | style      | 6.4.1        | [6.5.1](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/releases/tag/v6.5.1)             | 6.5.1   |                                                                                                                                                                          |
| eslint-plugin-only-error                  | style      | 1.0.2        |                                                                                               |         |                                                                                                                                                                          |
| eslint-plugin-react                       | style      | 7.26.0       | [7.28.0](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.28.0)               |         |                                                                                                                                                                          |
| eslint-plugin-react-hooks                 | style      | 4.2.0        | [4.3.0](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks)       |         |                                                                                                                                                                          |
| eslint-plugin-testing-library             | style      | 4.12.4       | [5.0.4](https://github.com/testing-library/eslint-plugin-testing-library/releases/tag/v5.0.4) |         |                                                                                                                                                                          |
| faker                                     | test       | 5.5.3        | [6.6.6](https://github.com/Marak/faker.js)                                                    | 5.5.3   | NOT UPDATED: There is no changelog so we do not have a way to assess the update other than try-and-catch                                                                 |
| husky                                     | style      | 1.3.1        | [7.0.4](https://github.com/typicode/husky/releases/tag/v7.0.4)                                | 1.3.1   | NOT UPDATED - The difference in versions is big, we better plan this ahead                                                                                               |
| identity-obj-proxy                        | other      | 3.0.0        |                                                                                               |         |                                                                                                                                                                          |
| jest                                      | test       | 26.6.3       |                                                                                               |         |                                                                                                                                                                          |
| jest-environment-jsdom-sixteen            | test       | 2.0.0        |                                                                                               |         |                                                                                                                                                                          |
| jest-junit                                | test       | 12.1.0       | [13.0.0](https://github.com/jest-community/jest-junit/releases/tag/v13.0.0)                   | 12.3.0  | [read more](https://github.com/jest-community/jest-junit/releases/tag/v12.3.0)                                                                                           |
| lint-staged                               | style      | 10.5.4       | [12.3.2](https://github.com/okonet/lint-staged/releases/tag/v12.3.2)                          | 10.5.4  | NOT UPDATED - The difference in versions is big, we better plan this ahead                                                                                               |
| normalize.css                             | build      | 8.0.1        |                                                                                               |         |                                                                                                                                                                          |
| postcss                                   | build      | 8.3.0        | [8.4.5](https://github.com/postcss/postcss/releases/tag/8.4.5)                                | 8.4.5   | They are using pnpm now                                                                                                                                                  |
| postcss-url                               | build      | 10.1.3       |                                                                                               |         |                                                                                                                                                                          |
| prettier                                  | style      | 2.3.0        | [2.5.1](https://github.com/prettier/prettier/releases/tag/2.5.1)                              |         |                                                                                                                                                                          |
| react                                     | other      | 16.13.1      | [17.0.2]()                                                                                    |         |                                                                                                                                                                          |
| react-cosmos                              | other      | 5.6.7        |                                                                                               |         |                                                                                                                                                                          |
| react-dom                                 | other      | 16.13.1      | [17.0.2]()                                                                                    |         |                                                                                                                                                                          |
| react-router                              | other      | 5.2.0        | [6.2.1]()                                                                                     |         |                                                                                                                                                                          |
| react-router-dom                          | other      | 5.2.0        | [6.2.1]()                                                                                     |         |                                                                                                                                                                          |
| react-scripts                             | other      | 4.0.3        | [5.0.0]()                                                                                     |         |                                                                                                                                                                          |
| react-test-renderer                       | test       | 16.13.1      | [17.0.2](https://github.com/facebook/react/releases/tag/v17.0.2)                              |         | Goes hand-in-hand with REACT                                                                                                                                             |
| resolve-path                              | build      | 1.4.0        |                                                                                               |         |                                                                                                                                                                          |
| rollup                                    | build      | 2.50.6       | [2.66.1](https://github.com/rollup/rollup/releases/tag/v2.66.1)                               | 2.66.1  |                                                                                                                                                                          |
| rollup-plugin-postcss                     | build      | 4.0.2        |                                                                                               |         |                                                                                                                                                                          |
| sass                                      | build      | 1.34.1       | [1.49.0](https://github.com/sass/dart-sass/releases/tag/1.49.0)                               | 1.49.0  |                                                                                                                                                                          |
| typescript                                | typescript | 4.3.2        | [4.5.5](https://github.com/microsoft/TypeScript/releases/tag/v4.5.5)                          | 4.5.5   |                                                                                                                                                                          |
| vercel                                    | build      | 22.0.1       | [23.1.2](https://github.com/vercel/vercel/releases/tag/vercel%4023.1.1)                       | 23.1.2  |                                                                                                                                                                          |
| webpack                                   | build      | 4.44.1       | [5.67.0]()                                                                                    |

## PR Author Checklist

- [ ] PR title adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [ ] I have finished reviewing the contents of this PR for accuracy
- [ ] If needed, I have included a [Changeset](https://github.com/changesets/changesets) and it follows [Semantic Versioning principles](https://semver.org/)
- [ ] I have completed all of the above and have enabled `auto-merge` for this PR

### CODE REVIEW

**Comment by brianespinosa** [comment]
@lordpixel I love the table outlining the changes and having notes. To me it seems like that would be perfect content to keep a record of in a directory as an ADR. What sort of process did you and @odiseo42 come up with for this so we can make sure we are tracking these decisions each month in the same way? I am not sure what to validate here, but this looks great and I think we should track this info in the code with a MD file and consistent process somehow.

**Comment by odiseo42** [comment]
> @lordpixel I love the table outlining the changes and having notes. To me it seems like that would be perfect content to keep a record of in a directory as an ADR. What sort of process did you and @odiseo42 come up with for this so we can make sure we are tracking these decisions each month in the same way? I am not sure what to validate here, but this looks great and I think we should track this info in the code with a MD file and consistent process somehow.

@brianespinosa Manu and I are having that conversation tomorrow. So this message comes right in time.

**Comment by lordpixel** [comment]
> @lordpixel I love the table outlining the changes and having notes. To me it seems like that would be perfect content to keep a record of in a directory as an ADR. What sort of process did you and @odiseo42 come up with for this so we can make sure we are tracking these decisions each month in the same way? I am not sure what to validate here, but this looks great and I think we should track this info in the code with a MD file and consistent process somehow.

@brianespinosa There is an md file at the root of the mono-repo, I added its contents to this PR's description just for informative purposes. The plan is to create an ADR document for each month.

Tomorrow, I will meet with @odiseo42 to discuss this and other processes together, we will keep you posted.

**Comment by brianespinosa** [comment]
@lordpixel is this PR going to come back in another form? I am not seeing a comment as to why this was closed.

**Pull request closed without merging**
