### PR TITLE
feat(FDS-526) Add footer to dashboard list widget

### PR DESCRIPTION
**Pull request by mementablog**
## PR Author Checklist

- [x] PR title adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [x] I have finished reviewing the contents of this PR for accuracy
- [x] If needed, I have included a [Changeset](https://github.com/changesets/changesets) and it follows [Semantic Versioning principles](https://semver.org/)
- [x] I have completed all of the above and have enabled `auto-merge` for this PR

### CODE REVIEW

**Comment by EspressiveGithub** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  **packages/cascara/src/components/Dashboard/DashboardDX.fixture.js**: This fixture has been changed.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0177e05290b626d752e34c4e29c92927882ed0d1
</p>

**Comment by mementablog** [comment]
Hello team, please check the changes in your local cosmos. I am attaching a test video so you can take a look at what's changing with this PR 
https://share.getcloudapp.com/OAujvxXB

**Review by rociobaena — APPROVED** [review]
LGTM!

**Review by ricardogonz — COMMENTED** [review]
LGTM

**Review by ricardogonz — APPROVED** [review]

**Pull request merged**
