### PR TITLE
feat(FDS-396): [ChatMessages] - use ramda instead of lodash 

### PR DESCRIPTION
**Pull request by lordpixel**
### Resolves [FDS-396](https://espressive.atlassian.net/browse/FDS-396).

Use Ramda instead of Lodash. This should have a decent impact on our bundle size as well, since lodash is pretty big and is not benefitted by tree shaking. This will also keep us using functional programming styles.

## PR Author Checklist

- [x] PR title adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [x] I have finished reviewing the contents of this PR for accuracy
- [x] If needed, I have included a [Changeset](https://github.com/changesets/changesets) and it follows [Semantic Versioning principles](https://semver.org/)
- [x] I have completed all of the above and have enabled `auto-merge` for this PR

### CODE REVIEW

**Review by rociobaena — APPROVED** [review]
pathOr looks interesting 🧐

**Review by brianespinosa — CHANGES_REQUESTED** [review]
This is great. I can see that we are removing the use of lodash in the code. If this is done, the only thing missing is we need to remove lodash from our dependencies in all package.json or else we are still forcing people to install it and making it available for people to use.

In addition to removing it, I think it would be good for us to make a repo specific eslint rule to let people know that we have deprecated lodash in favor of ramda. This could be a separate change if you want, but we should at the very least remove lodash from package.json files.

**Comment by lordpixel** [comment]
> This is great. I can see that we are removing the use of lodash in the code. If this is done, the only thing missing is we need to remove lodash from our dependencies in all package.json or else we are still forcing people to install it and making it available for people to use.
> 
> In addition to removing it, I think it would be good for us to make a repo specific eslint rule to let people know that we have deprecated lodash in favor of ramda. This could be a separate change if you want, but we should at the very least remove lodash from package.json files.

@brianespinosa `lodash` was not pesent in any package.json.

**Review by brianespinosa — APPROVED** [review]
Thanks for checking, @lordpixel Approving

**Pull request merged**
