### PR TITLE
feature(FDS-342): Input range field

### PR DESCRIPTION
**Pull request by rociobaena**
The input range type is adding to our module list.
This PR includes:
- Module DataRange
- Fixture
- Unit test

### Snapshots
A new fixture for the DataRange field is created.

## New Component Checklist

- [x] Includes unit tests for _ALL_ required FDS use cases
- [x] Does not mute any top level API props in React
- [x] Includes an explanation for any changes to Jest snapshots (should be a PR tag automatically added if this happens)
- [-] Component uses `React.forwardRef()` when a single DOM node is returned, _AND_ it makes React-sense to access that DOM node

### CODE REVIEW

**Review by lordpixel — DISMISSED** [review]
👍

**Review by brianespinosa — APPROVED** [review]

**Review by brianespinosa — CHANGES_REQUESTED** [review]
conflicts

**Review by brianespinosa — APPROVED** [review]
Conflicts resolved

**Review by lordpixel — APPROVED** [review]

**Comment by brianespinosa** [comment]
@rociobaena all other PRs are in. This little one just needs that snap updated and it should be good to go! 🙌🏽

**Review by brianespinosa — APPROVED** [review]

**Review by lordpixel — APPROVED** [review]

**Review by brianespinosa — APPROVED** [review]

**Pull request merged**
