### PR TITLE
 feat(fds-531) Updates admin navigation UI styling to match spike DEV-20975

### PR DESCRIPTION
**Pull request by mementablog**
This PR introduces the changes in the navigation to match the proposal of the spike DEV-20975: Admin Navigation UI Styling
https://espressive.atlassian.net/browse/DEV-20975 

## PR Author Checklist

- [x] PR title adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [x] I have finished reviewing the contents of this PR for accuracy
- [x] If needed, I have included a [Changeset](https://github.com/changesets/changesets) and it follows [Semantic Versioning principles](https://semver.org/)
- [x] I have completed all of the above and have enabled `auto-merge` for this PR

### CODE REVIEW

**Comment by EspressiveGithub** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  **packages/cascara/src/structures/AdminStructure/components/Nav/Nav.fixture.js**: This fixture has been changed.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a058f945080c64e02320ea57b40ee7499b479ef5
</p>

**Comment by mementablog** [comment]
Hi! This is how the changes in the navbar look. Attaching a video  here to review the changes with @CaffeinatedAllie and all the other members of the team interested 
https://share.getcloudapp.com/L1u6zyLd

**Review by ichbinedgar — APPROVED** [review]
i guess they are ok, hehe

**Comment by mementablog** [comment]
@rociobaena We need your review here

**Pull request closed without merging**
