### PR TITLE
feat(FDS-528) Add singleLined prop to table

### PR DESCRIPTION
**Pull request by mementablog**
This prop simplifies the UI for the rows in the table and is the counterpart of our *Striped* style in the Cascara Table.

We also made the Selections checkboxes bigger 'width: 24px'
And update selections fixtures to add a singleLined fixture

**Using singleLined prop**

With singleLined prop

**Without singleLined prop (default table)**

Without singleLined prop
image

## PR Author Checklist

- [x] PR title adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [x] I have finished reviewing the contents of this PR for accuracy
- [x] If needed, I have included a [Changeset](https://github.com/changesets/changesets) and it follows [Semantic Versioning principles](https://semver.org/)
- [x] I have completed all of the above and have enabled `auto-merge` for this PR

### CODE REVIEW

**Comment by EspressiveGithub** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  **packages/cascara/src/components/Table/fixtures/Selection.fixture.js**: This fixture has been changed.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 290065c6c9d435229f531770f789efe48c29cad6
</p>

**Review by rociobaena — DISMISSED** [review]
LGTM!!

**Review by ricardogonz — APPROVED** [review]
LGTM

**Review by rociobaena — APPROVED** [review]
Great!!

**Pull request merged**
